server:
  port: 8080

spring:
  application:
    name: healtry
  datasource:
    url: jdbc:mariadb://localhost:3306/healtry?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    open-in-view: true
    show-sql: true

#  web:
#    cors:
#      allowed-origins: http://localhost:8083
#      allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
#      allowed-headers: '*'
#      allow-credentials: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE